  services:
    cli:
      container_name: cli
      build: .
      tty: true
      volumes:
        - ./:/code
      environment:
        - ENVIRONMENT=${ENVIRONMENT}
        - DATABENTO_API_KEY=${DATABENTO_API_KEY}
